### ISSUE TITLE
Speed of training

### ISSUE THREAD

**Issue by ewindso** [fmathey/novabrain#2]
Hello!  Thanks for making this library.  I was wondering if there was a way to speed up training a bit, as sometimes when I have different types of data going in, it can take a few minutes to hours to train...  like maybe saving the data, and then "appending" new data as it comes in?  (I'm fairly new to neural networks.)  Thanks!

**Comment by fmathey** [comment]
Hello, actually I noticed this problem there is little time testing the recognition. I have not had time to look for the solution . I will look into the problem quickly . Thank you very much for your return :-)

**Comment by ewindso** [comment]
Great, thanks!

**Comment by fmathey** [comment]
I did some training optimizations. They are available in version 0.8.2 . I do not think the problem is fully resolved but it should still be felt.
